# Generated by Django 5.0.3 on 2024-03-23 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('photo', models.CharField(max_length=2000, verbose_name='Путь до изображения')),
                ('max_load', models.PositiveSmallIntegerField(verbose_name='Максимальный вес')),
                ('power_reserve', models.PositiveSmallIntegerField(verbose_name='Запас хода')),
                ('max_speed', models.PositiveSmallIntegerField(verbose_name='Максимальная скорость')),
                ('watt_power', models.PositiveIntegerField(verbose_name='Мощьность')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_to_product', to='manufacturer.manufacturer', verbose_name='Производитель')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type_to_product', to='product.producttype', verbose_name='Тип товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'products',
            },
        ),
    ]
